Activity-1

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("addition")
print(a+b)
print("subraction")
print(a-c)
print("multiplication")
print(a*b*c)
print("division")
print(b/c)



addition
[5 7 9]
subraction
[-6 -6 -6]
multiplication
[ 28  80 162]
division
[0.57142857 0.625      0.66666667]
